language: python
python:
  - "2.7"
env:
  - DATABASE_URL=postgres://postgres:@localhost:5432/indigo_test
before_install:
  - "rvm install ruby-2.1.6"
  - "rvm use ruby-2.1.6"
install: 
  - "pip install -r requirements.txt"
  - "bundle install"
before_script:
  - "npm install -g jshint"
script: python manage.py test && jshint indigo_app/static/javascript/indigo/
